services:
  db:
    image: postgres:17.2
    hostname: localhost
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-db-data:/var/lib/postgresql/data
